# Generated by Django 4.1 on 2023-10-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detail', '0001_initial'),
    ]

    