# Generated by Django 4.1 on 2023-10-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detail', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('Contact', models.BigIntegerField()),
                ('message', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
